<?php

/** @var Magento\Framework\View\Element\Template\ $block */

?>
<script type="text/x-magento-init">
    {
        "*" : {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Elogic_Test/js/plain-view-model"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
    <ul data-bind="foreach: exchange_rates">
        <li data-bind="text: $data"></li>
    </ul>
</div>