<?php
/** @var \Maxime\Jobs\Model\Department $department */
$department = $this->getLoadedDepartmentCollection();

$iterator = 1;
$total = $department->getJobsCount();
?>
<div class="department-view">
    <div class="department_name">
        <?= __('Department :') ?>
        <h1><?= $department->getTitle() ?></h1>
    </div>
    <div class="department_desctiprion">
        <?= $department->getDescription() ?>
    </div>
</div>
<div class="job-wrapper">
    <ol class="jobs list">
        <?php foreach ($jobCollection as $job): ?>
            <li class="item<?= ($iterator == 1) ? ' first' : '' ?><?= ($total == $iterator) ? ' last' : '' ?>">
                <div class="title">
                    <a href="<?= $this->getJobUrl($job) ?>" title="<?= $job->getTitle() ?>">
                        <?= $job->getTitle() ?>
                    </a>
                </div>
                <div class="department_name">
                    <?= __('Department : ') ?>
                    <a href="<?= $this->getDepartmentUrl($job) ?>" title="<?= $job->getDepartmentName() ?>">
                        <?= $job->getDepartmentName() ?>
                    </a>
                </div>
                <div class="type"><?= $job->getType() ?></div>
                <div class="location"><?= $job->getLocation() ?></div>
                <div class="date"><?= $this->formatDate($job->getDate()) ?></div>
                <div class="description"><?= $job->getDescription() ?></div>
            </li>
            <?php $iterator++; ?>
        <?php endforeach; ?>
    </ol>
</div>
