<?php

/** @var Magento\Framework\View\Element\Template\ $block */

?>
<script type="text/x-magento-init">
    {
        "*" : {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Elogic/Js/plain-view-model"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>
</div>