<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Elogic\Vendors\Model\Vendor;

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 * @var $_vendor Vendor
 *
 */
?>
<?php
$_vendor = $block->getVendor();

if ($_vendor && $_vendor instanceof Vendor) :
    $_name = $_vendor->getData('name');
?>
        <div class="product attribute vendor-image hover-image">
            <img src="<?= $_vendor->getLogoUrl() ?>"  alt="<?= $_name ?>" class="hover-image">
            <div class="image-text hover-text">
                <h1> <?= $_name ?></h1>
                <h6 class="value"> <?= $_vendor->getData('description') ?></h6>
            </div>
        </div>
<?php endif; ?>
