<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
use Elogic\Vendors\Helper\FrontOutput;
use Elogic\Vendors\Model\Vendor;

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 * @var $_vendor Vendor
 *
 */
?>
<?php
/** @var FrontOutput $_helper */
$_helper = $this->helper(FrontOutput::class);
$_vendor = $block->getVendor();

if ($_vendor && $_vendor instanceof Vendor) :
    $_name          = $_vendor->getData('name');
?>
        <div class="product attribute vendor-image">
            <img src="<?= $_vendor->getLogoUrl() ?>"  alt="<?= $_name ?>" class="hover-image">
        </div>
        <div class="product attribute text hover-text">
            <h1> <?= $_name ?></h1>
            <h6 class="value"> <?= $_vendor->getData('description') ?></h6>
        </div>
<?php endif; ?>
